var searchData=
[
  ['in_20a_20web_20browser_0',['This project contains a wator.go file that contains all code used to create the simulation and output the benchmark results. It also contains a main.go file used to run the wator.go simulation. This was done to allow for godoc to be used for the Wator package. To view the godoc, navigate to the WatorProject directory in the terminal, run the command &apos;godoc -http=:6060&apos;, search &apos;http://localhost:6060/pkg/wator/wator/&apos; in a web browser.',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['in_20terminal_20run_20using_20command_20go_20run_1',['Navigate to folder containing file in terminal. Run using command &quot;go run .&quot;.',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['in_20the_20html_20folder_20titles_20index_20html_2',['Doxygen created webpage can be located in the html folder, titles index.html',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['in_20the_20same_20directory_20as_20source_20code_3',['Go code demonstrating the Wator simulation with graphical representation. Benchmarking performed with the simulation running on one, two, four and eight threads, and benchmarking results are saved to benchmark_results.xlsx in the same directory as source code.',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['in_20the_20terminal_20run_20the_20command_20godoc_20http_20_3a6060_20search_20http_3a_20localhost_3a6060_20pkg_20wator_20wator_20in_20a_20web_20browser_4',['This project contains a wator.go file that contains all code used to create the simulation and output the benchmark results. It also contains a main.go file used to run the wator.go simulation. This was done to allow for godoc to be used for the Wator package. To view the godoc, navigate to the WatorProject directory in the terminal, run the command &apos;godoc -http=:6060&apos;, search &apos;http://localhost:6060/pkg/wator/wator/&apos; in a web browser.',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['index_20html_5',['Doxygen created webpage can be located in the html folder, titles index.html',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['instructions_6',['Instructions',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['is_20licensed_20under_20cc_20by_20sa_204_200_7',['wator.go © 2024 by Seán Rourke is licensed under CC BY-SA 4.0 .',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['issues_8',['Known Issues',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['it_20also_20contains_20a_20main_20go_20file_20used_20to_20run_20the_20wator_20go_20simulation_20this_20was_20done_20to_20allow_20for_20godoc_20to_20be_20used_20for_20the_20wator_20package_20to_20view_20the_20godoc_20navigate_20to_20the_20watorproject_20directory_20in_20the_20terminal_20run_20the_20command_20godoc_20http_20_3a6060_20search_20http_3a_20localhost_3a6060_20pkg_20wator_20wator_20in_20a_20web_20browser_9',['This project contains a wator.go file that contains all code used to create the simulation and output the benchmark results. It also contains a main.go file used to run the wator.go simulation. This was done to allow for godoc to be used for the Wator package. To view the godoc, navigate to the WatorProject directory in the terminal, run the command &apos;godoc -http=:6060&apos;, search &apos;http://localhost:6060/pkg/wator/wator/&apos; in a web browser.',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]]
];
