var searchData=
[
  ['demonstrating_20the_20wator_20simulation_20with_20graphical_20representation_20benchmarking_20performed_20with_20the_20simulation_20running_20on_20one_20two_20four_20and_20eight_20threads_20and_20benchmarking_20results_20are_20saved_20to_20benchmark_5fresults_20xlsx_20in_20the_20same_20directory_20as_20source_20code_0',['Go code demonstrating the Wator simulation with graphical representation. Benchmarking performed with the simulation running on one, two, four and eight threads, and benchmarking results are saved to benchmark_results.xlsx in the same directory as source code.',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['description_1',['Description',['../md__r_e_a_d_m_e.html',1,'']]],
  ['directory_20as_20source_20code_2',['Go code demonstrating the Wator simulation with graphical representation. Benchmarking performed with the simulation running on one, two, four and eight threads, and benchmarking results are saved to benchmark_results.xlsx in the same directory as source code.',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['directory_20in_20the_20terminal_20run_20the_20command_20godoc_20http_20_3a6060_20search_20http_3a_20localhost_3a6060_20pkg_20wator_20wator_20in_20a_20web_20browser_3',['This project contains a wator.go file that contains all code used to create the simulation and output the benchmark results. It also contains a main.go file used to run the wator.go simulation. This was done to allow for godoc to be used for the Wator package. To view the godoc, navigate to the WatorProject directory in the terminal, run the command &apos;godoc -http=:6060&apos;, search &apos;http://localhost:6060/pkg/wator/wator/&apos; in a web browser.',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['documentation_20but_20does_20not_20read_20the_20doxygen_20formatted_20comments_20to_20create_20documentation_20so_20webpages_20remain_20empty_4',['Doxygen creates the webpage for documentation, but does not read the Doxygen formatted comments to create documentation, so webpages remain empty.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['documentation_20so_20webpages_20remain_20empty_5',['Doxygen creates the webpage for documentation, but does not read the Doxygen formatted comments to create documentation, so webpages remain empty.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['does_20not_20read_20the_20doxygen_20formatted_20comments_20to_20create_20documentation_20so_20webpages_20remain_20empty_6',['Doxygen creates the webpage for documentation, but does not read the Doxygen formatted comments to create documentation, so webpages remain empty.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['done_20to_20allow_20for_20godoc_20to_20be_20used_20for_20the_20wator_20package_20to_20view_20the_20godoc_20navigate_20to_20the_20watorproject_20directory_20in_20the_20terminal_20run_20the_20command_20godoc_20http_20_3a6060_20search_20http_3a_20localhost_3a6060_20pkg_20wator_20wator_20in_20a_20web_20browser_7',['This project contains a wator.go file that contains all code used to create the simulation and output the benchmark results. It also contains a main.go file used to run the wator.go simulation. This was done to allow for godoc to be used for the Wator package. To view the godoc, navigate to the WatorProject directory in the terminal, run the command &apos;godoc -http=:6060&apos;, search &apos;http://localhost:6060/pkg/wator/wator/&apos; in a web browser.',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['doxygen_20created_20webpage_20can_20be_20located_20in_20the_20html_20folder_20titles_20index_20html_8',['Doxygen created webpage can be located in the html folder, titles index.html',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['doxygen_20creates_20the_20webpage_20for_20documentation_20but_20does_20not_20read_20the_20doxygen_20formatted_20comments_20to_20create_20documentation_20so_20webpages_20remain_20empty_9',['Doxygen creates the webpage for documentation, but does not read the Doxygen formatted comments to create documentation, so webpages remain empty.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['doxygen_20formatted_20comments_20to_20create_20documentation_20so_20webpages_20remain_20empty_10',['Doxygen creates the webpage for documentation, but does not read the Doxygen formatted comments to create documentation, so webpages remain empty.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]]
];
